spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account-service
              uri: http://account-service:8081
              predicates:
                - Path=/api/accounts/**
            - id: blindbox-service
              uri: http://blindbox-service:8082
              predicates:
                - Path=/api/blind-boxes/**
            - id: brand-service
              uri: http://brand-service:8083
              predicates:
                - Path=/api/brands/**

