spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: MSAccount_SE184931
              uri: http://localhost:8081
              predicates:
                - Path=/api/accounts/**
            - id: MSBlindBox_SE184931
              uri: http://localhost:8082
              predicates:
                - Path=/api/blind-boxes/**
            - id: MSBrand_SE184931
              uri: http://localhost:8083
              predicates:
                - Path=/api/brands/**

